# External Blockchain Configuration for Vision Node
# Using Electrum protocol for lightweight blockchain queries

[btc]
backend = "electrum"
servers = [
  "ssl://electrum.blockstream.info:50002"
]

[bch]
backend = "electrum"
servers = [
  "ssl://cashnode.bch.ninja:50002",
  "ssl://fulcrum.aglauck.com:50002"
]

[doge]
backend = "electrum"
servers = [
  "ssl://doge.aftrek.org:50002",
  "ssl://electrum1.cipig.net:20060"
]
